server:
  port: ${PORT:8080}

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@tech-challenge-cluster.0axax8s.mongodb.net/order?retryWrites=true&w=majority&appName=tech-challenge-cluster